# Docker Compose equivalent of the Vagrant CentOS 7 VM (Part 1)
# Replaces: vagrant up / vagrant ssh / vagrant halt / vagrant destroy

services:
  centos_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: centos.server.local
    hostname: centos-server
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
    stdin_open: true
    tty: true
